### ISSUE TITLE
Refactoring home screen

### ISSUE THREAD

**Issue by yujinkim1** [GDSC-SKHU/98developers-flutter-app#24]
## Summary
- Material 3 디자인에서 권장하는 Flutter UI를 활용할거에요.
- 화면에 나타나는 위젯을 정리할거에요.
- 코드를 간소화할거에요.

## Requirements
- [x] Dynamic theme 적용
- [x] 불필요한 코드라인 제거

**Comment by yujinkim1** [comment]
## Image
> 첫번째 작업을 마친 상태의 홈 스크린이에요. @devpark435 , @yeeZinu , @LEEHYUNBOK 

<p align="center">
<img width="426" alt="Screen Shot 2023-02-28 at 23 54 10" src="https://user-images.githubusercontent.com/26790710/221891239-5f3a3321-2aef-4f53-a378-63c2e9872a1c.png">
</p>

**Comment by yujinkim1** [comment]
## Prototype Image
> 3차 피드백이 반영된 홈 스크린이에요.

<p align="center">
<img width="426" src="https://user-images.githubusercontent.com/26790710/222137214-a6d80e37-5d2f-4ee4-9446-161f91368100.png">
</p>

**Comment by yujinkim1** [comment]
> * [ ]  Carous card slider 위젯 분리
> * [ ]  위젯과 이벤트 분리

@devpark435 상태 관리 코드를 리팩토링 단계에서 거치지 않고, 데이터 연결 작업 시 blocbuilder 사용해서 cubit을 사용해보는 것이 좋을 것 같다는 의견을 주었어요.

두 항목은 제외시킬게요.

**Comment by devpark435** [comment]
> 3차 피드백 반영 작업본이에요

<p align="center">
<img width=412 src="https://user-images.githubusercontent.com/112539563/222320650-c26c468a-fec9-4e4c-8709-b0886ef4e8bf.png" />
</p>
