### ISSUE TITLE
Refactoring profile screen

### ISSUE THREAD

**Issue by yujinkim1** [GDSC-SKHU/98developers-flutter-app#28]
## Summary
- Material 3 디자인에서 권장하는 Flutter UI를 활용할거에요.
- 화면에 나타나는 위젯을 정리할거에요.
- 코드를 간소화할거에요.

## Requirements
- [x] Dynamic theme 적용
- [x] 불필요한 코드라인 제거
- [x] Material 3에서 권장하는 메뉴 접근 방식 선택

**Comment by yujinkim1** [comment]
## Prototype Image
> 2차 피드백이 반영되었어요.

<p align="center">
<img src="https://user-images.githubusercontent.com/26790710/222142873-2a9f1de3-3e93-4925-a3c6-1036ec1864df.png" />
</p>

**Comment by devpark435** [comment]
> 2차 피드백 반영 작업본

<p align="center">
<img width=412 src="https://user-images.githubusercontent.com/112539563/222319747-354f314f-e69a-4e62-a5a6-3a8f42f22a2f.png" />
</p>
