### ISSUE TITLE
Implementing 결제 시스템 연동

### ISSUE THREAD

**Issue by yujinkim1** [GDSC-SKHU/98developers-flutter-app#38]
## Summary
- 결제 시스템을 클라이언트와 연동하는 작업을 진행해요.
- 국내 결제원을 사용하기 위해 토스 페이먼츠를 활용해요.
- 그 외로 Google pay, Apple pay가 있어요.

**Comment by yujinkim1** [comment]
## Additional
- 토스 페이먼츠는 `url_launcher` 패키지를 활용해 웹뷰 형태로 PG사 결제를 지원해요.
- 각 PG사는 계약자에게 고유한 키를 발급해요. 이 키는 PG사와 협약이 되어 있는 상태여야 해요.
- 여러 가지 복잡성으로 인해 안전한 결제 시스템을 알아봐야 해요.
- 그 중 Flutter 환경에서 준공식적으로 지원하고 있는 부트페이가 있어요. 부트페이는 대한민국 내 결제 서비스를 원활하게 진행되도록 해요.
- 또 국내 개인정보보호법과 전자상거래 등에서의 소비자보호에 관한 법률과 규정을 숙지해야해요.
- 결제 시 필요한 개인정보를 적절하게 수집하고 보호해야 해요.

**Comment by yujinkim1** [comment]
> 내용 추가
## Additional
- 토스 페이먼츠는 `url_launcher` 패키지를 활용해 웹뷰 형태로 PG사 결제를 지원해요.
- 각 PG사는 계약자에게 고유한 키를 발급해요. 이 키는 PG사와 협약이 되어 있는 상태여야 해요.
- 여러 가지 복잡성으로 인해 안전한 결제 시스템을 알아봐야 해요.
- 그 중 Flutter 환경에서 비공식적으로 조금이나마 안전하게 지원하고 있는 부트페이가 있어요. 
- 부트페이를 사용하면 Flutter에서 대한민국 내 결제 서비스를 원활하게 유지할 수 있어요.
- 그렇지만, PG사 계약이 이루어져야 실 사용이 가능해요.
- 구글 페이 및 애플 페이는 결제대행업체를 알아봐야해요.
- 결제대행업체는 AOS, iOS 기준으로 나뉘어져 있어요.
- 인앱 결제 방식도 존재해요.
- 또 국내 개인정보보호법과 전자상거래 등에서의 소비자보호에 관한 법률과 규정을 숙지해야해요.
- 결제 시 필요한 개인정보를 적절하게 수집하고 보호해야 해요.

**Comment by devpark435** [comment]
## Content
- [x] Boot Pay 를 통한 결제 호출 인터페이스 제작
- [x] Boot Pay 연동 후 테스트 결제 확인
- [x] 결제 후 취소 가능 여부 확인
- [x] 결제 완료시 회원 정보 대시보드 업로드 확인

**Comment by yujinkim1** [comment]
- #52
