### ISSUE TITLE
Implementing challenges

### ISSUE THREAD

**Issue by devpark435** [GDSC-SKHU/98developers-flutter-app#43]
- [x] cubit 활용 challenges api 불러오기
- [x] challenge list refactoring 
- [x] enroll screen 추가하기
- [x] 등록 버튼 클릭시 챌린지 참가 구현
- [x] 챌린지 참여 후 이미지 업로드 기능 확인

**Comment by yujinkim1** [comment]
@devpark435 고생 했어요👍
