### ISSUE TITLE
Launch Screen

### ISSUE THREAD

**Issue by yujinkim1** [GDSC-SKHU/98developers-flutter-app#5]
## Summary
- Launch Screen은 앱 실행 시 처음 보여지는 화면이에요.
- 간단한 사용 메뉴얼을 포함한 4단계의 Pagination을 포함해요.
- 마지막 Section은 Initial Screen으로 연결되어요.

## Requirements
- [x] styling/launch 브랜치 생성
- [x] 파일 생성
- [x] Page1-첫번째 기능 메뉴얼
- [x] Page2-두번째 기능 메뉴얼
- [x] Page3-세번째 기능 메뉴얼 & Initial Screen 이동 버튼
- [x] Smooth 선형 Progress indicator 적용

**Comment by yujinkim1** [comment]
<p align="center">
<img src="https://user-images.githubusercontent.com/26790710/219035295-a42054dc-9645-4888-ae3b-1945f7cb5996.png" />
</p>

**Comment by yujinkim1** [comment]
### Prototype Image2
> 수정사항이 반영되었어요.

<p align="center">
<img src="https://user-images.githubusercontent.com/26790710/219864057-94497fed-1893-41df-8044-1a41037cdd5a.png" />
</p>

**Comment by yujinkim1** [comment]
## Need to add
- [x] constant 유틸리티 생성(padding, spacing, image path)
- [x] skip 버튼
- [ ] text animation
- [x] dot indicator 삭제
- [x] animation progress indicator 적용

**Comment by yujinkim1** [comment]
https://user-images.githubusercontent.com/26790710/221398202-1ee6d265-86d9-4b03-85b3-47e1c0a3c91f.mov

**Comment by yujinkim1** [comment]
- [x] #13

**Comment by devpark435** [comment]
아주 깔끔하네용
